# This is a basic workflow to help you get started with Actions

name: Basic Workflow

# Controls when the workflow will run
on:
    push:
    workflow_dispatch:


jobs:
 
  echo-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run main from from repor
        run: |
             ls -l
             pwd
             bash main
